remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Tom Igoe's GitHub Repositories
description:  Search my gitHub account:
  <input type="text" id="searchbox" onchange="search();" target="_blank">
  <a href="" id="searcher" class="button">search</a>
    <script>
    function search() {
      let url = 'https://github.com/search/advanced?q=user%3Atigoe+';
      let term = document.getElementById('searchbox').value;
      url += term;
      url += '&type=Repositories&ref=advsearch&l=&l=';
      let mySearchLink = document.getElementById("searcher");
      mySearchLink.href = url;
      mySearchLink.click();
    }
  </script> 